version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_HOST=mongodb
      - MONGO_DBNAME=${MONGO_DBNAME}
      - PORT=${PORT}
    ports:
      - "1323:1323"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    expose:
      - 27017
    