version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "1323:1323"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"